<?php

use App\Enums\RiskLevel;

return [
    'providers' => [
        'mockoon' => [
            'room_sensor_data_url' => 'http://host.docker.internal:3001/room',
        ],
    ],
    'limits' => [
        'carbonDioxide' => [
            0 => RiskLevel::NO_RISK->riskRating(),
            350 => RiskLevel::LOW->riskRating(),
            1000 => RiskLevel::MEDIUM->riskRating(),
            2000 => RiskLevel::HIGH->riskRating(),
            5000 => RiskLevel::CRITICAL->riskRating(),
        ],
        'humidity' => [
            0 => [
                'temperature' => [
                    16 => RiskLevel::CRITICAL->riskRating(),
                    17 => RiskLevel::CRITICAL->riskRating(),
                    18 => RiskLevel::CRITICAL->riskRating(),
                    19 => RiskLevel::CRITICAL->riskRating(),
                    20 => RiskLevel::CRITICAL->riskRating(),
                    21 => RiskLevel::CRITICAL->riskRating(),
                    22 => RiskLevel::CRITICAL->riskRating(),
                    23 => RiskLevel::CRITICAL->riskRating(),
                    24 => RiskLevel::CRITICAL->riskRating(),
                    25 => RiskLevel::CRITICAL->riskRating(),
                    26 => RiskLevel::CRITICAL->riskRating(),
                    27 => RiskLevel::CRITICAL->riskRating(),
                    28 => RiskLevel::CRITICAL->riskRating(),
                ],
            ],
            10 => [
                'temperature' => [
                    16 => RiskLevel::CRITICAL->riskRating(),
                    17 => RiskLevel::CRITICAL->riskRating(),
                    18 => RiskLevel::CRITICAL->riskRating(),
                    19 => RiskLevel::CRITICAL->riskRating(),
                    20 => RiskLevel::CRITICAL->riskRating(),
                    21 => RiskLevel::CRITICAL->riskRating(),
                    22 => RiskLevel::CRITICAL->riskRating(),
                    23 => RiskLevel::CRITICAL->riskRating(),
                    24 => RiskLevel::CRITICAL->riskRating(),
                    25 => RiskLevel::CRITICAL->riskRating(),
                    26 => RiskLevel::CRITICAL->riskRating(),
                    27 => RiskLevel::CRITICAL->riskRating(),
                    28 => RiskLevel::CRITICAL->riskRating(),
                ],
            ],
            20 => [
                'temperature' => [
                    16 => RiskLevel::CRITICAL->riskRating(),
                    17 => RiskLevel::CRITICAL->riskRating(),
                    18 => RiskLevel::CRITICAL->riskRating(),
                    19 => RiskLevel::CRITICAL->riskRating(),
                    20 => RiskLevel::CRITICAL->riskRating(),
                    21 => RiskLevel::CRITICAL->riskRating(),
                    22 => RiskLevel::CRITICAL->riskRating(),
                    23 => RiskLevel::CRITICAL->riskRating(),
                    24 => RiskLevel::CRITICAL->riskRating(),
                    25 => RiskLevel::CRITICAL->riskRating(),
                    26 => RiskLevel::CRITICAL->riskRating(),
                    27 => RiskLevel::CRITICAL->riskRating(),
                    28 => RiskLevel::CRITICAL->riskRating(),
                ],
            ],
            30 => [
                'temperature' => [
                    16 => RiskLevel::CRITICAL->riskRating(),
                    17 => RiskLevel::CRITICAL->riskRating(),
                    18 => RiskLevel::CRITICAL->riskRating(),
                    19 => RiskLevel::HIGH->riskRating(),
                    20 => RiskLevel::HIGH->riskRating(),
                    21 => RiskLevel::HIGH->riskRating(),
                    22 => RiskLevel::HIGH->riskRating(),
                    23 => RiskLevel::HIGH->riskRating(),
                    24 => RiskLevel::HIGH->riskRating(),
                    25 => RiskLevel::HIGH->riskRating(),
                    26 => RiskLevel::HIGH->riskRating(),
                    27 => RiskLevel::CRITICAL->riskRating(),
                    28 => RiskLevel::CRITICAL->riskRating(),
                ],
            ],
            40 => [
                'temperature' => [
                    16 => RiskLevel::CRITICAL->riskRating(),
                    17 => RiskLevel::CRITICAL->riskRating(),
                    18 => RiskLevel::CRITICAL->riskRating(),
                    19 => RiskLevel::HIGH->riskRating(),
                    20 => RiskLevel::MEDIUM->riskRating(),
                    21 => RiskLevel::MEDIUM->riskRating(),
                    22 => RiskLevel::MEDIUM->riskRating(),
                    23 => RiskLevel::LOW->riskRating(),
                    24 => RiskLevel::LOW->riskRating(),
                    25 => RiskLevel::MEDIUM->riskRating(),
                    26 => RiskLevel::HIGH->riskRating(),
                    27 => RiskLevel::CRITICAL->riskRating(),
                    28 => RiskLevel::CRITICAL->riskRating(),
                ],
            ],
            50 => [
                'temperature' => [
                    16 => RiskLevel::CRITICAL->riskRating(),
                    17 => RiskLevel::CRITICAL->riskRating(),
                    18 => RiskLevel::HIGH->riskRating(),
                    19 => RiskLevel::MEDIUM->riskRating(),
                    20 => RiskLevel::LOW->riskRating(),
                    21 => RiskLevel::NO_RISK->riskRating(),
                    22 => RiskLevel::NO_RISK->riskRating(),
                    23 => RiskLevel::NO_RISK->riskRating(),
                    24 => RiskLevel::LOW->riskRating(),
                    25 => RiskLevel::MEDIUM->riskRating(),
                    26 => RiskLevel::HIGH->riskRating(),
                    27 => RiskLevel::CRITICAL->riskRating(),
                    28 => RiskLevel::CRITICAL->riskRating(),
                ],
            ],
            60 => [
                'temperature' => [
                    16 => RiskLevel::CRITICAL->riskRating(),
                    17 => RiskLevel::HIGH->riskRating(),
                    18 => RiskLevel::MEDIUM->riskRating(),
                    19 => RiskLevel::LOW->riskRating(),
                    20 => RiskLevel::NO_RISK->riskRating(),
                    21 => RiskLevel::NO_RISK->riskRating(),
                    22 => RiskLevel::NO_RISK->riskRating(),
                    23 => RiskLevel::LOW->riskRating(),
                    24 => RiskLevel::LOW->riskRating(),
                    25 => RiskLevel::MEDIUM->riskRating(),
                    26 => RiskLevel::HIGH->riskRating(),
                    27 => RiskLevel::CRITICAL->riskRating(),
                    28 => RiskLevel::CRITICAL->riskRating(),
                ],
            ],
            70 => [
                'temperature' => [
                    16 => RiskLevel::CRITICAL->riskRating(),
                    17 => RiskLevel::HIGH->riskRating(),
                    18 => RiskLevel::MEDIUM->riskRating(),
                    19 => RiskLevel::LOW->riskRating(),
                    20 => RiskLevel::NO_RISK->riskRating(),
                    21 => RiskLevel::NO_RISK->riskRating(),
                    22 => RiskLevel::NO_RISK->riskRating(),
                    23 => RiskLevel::LOW->riskRating(),
                    24 => RiskLevel::MEDIUM->riskRating(),
                    25 => RiskLevel::HIGH->riskRating(),
                    26 => RiskLevel::HIGH->riskRating(),
                    27 => RiskLevel::CRITICAL->riskRating(),
                    28 => RiskLevel::CRITICAL->riskRating(),
                ],
            ],
            80 => [
                'temperature' => [
                    16 => RiskLevel::CRITICAL->riskRating(),
                    17 => RiskLevel::HIGH->riskRating(),
                    18 => RiskLevel::LOW->riskRating(),
                    19 => RiskLevel::LOW->riskRating(),
                    20 => RiskLevel::LOW->riskRating(),
                    21 => RiskLevel::LOW->riskRating(),
                    22 => RiskLevel::LOW->riskRating(),
                    23 => RiskLevel::MEDIUM->riskRating(),
                    24 => RiskLevel::HIGH->riskRating(),
                    25 => RiskLevel::CRITICAL->riskRating(),
                    26 => RiskLevel::CRITICAL->riskRating(),
                    27 => RiskLevel::CRITICAL->riskRating(),
                    28 => RiskLevel::CRITICAL->riskRating(),
                ],
            ],
            90 => [
                'temperature' => [
                    16 => RiskLevel::CRITICAL->riskRating(),
                    17 => RiskLevel::CRITICAL->riskRating(),
                    18 => RiskLevel::HIGH->riskRating(),
                    19 => RiskLevel::MEDIUM->riskRating(),
                    20 => RiskLevel::MEDIUM->riskRating(),
                    21 => RiskLevel::MEDIUM->riskRating(),
                    22 => RiskLevel::MEDIUM->riskRating(),
                    23 => RiskLevel::HIGH->riskRating(),
                    24 => RiskLevel::HIGH->riskRating(),
                    25 => RiskLevel::CRITICAL->riskRating(),
                    26 => RiskLevel::CRITICAL->riskRating(),
                    27 => RiskLevel::CRITICAL->riskRating(),
                    28 => RiskLevel::CRITICAL->riskRating(),
                ],
            ],
        ],
    ],
];
